name: Valid JSON

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validate JSON
      run: docker run --rm -v "$PWD:/host" -w /host swift:5.3 swift validate.swift
      env:
        DEVELOPER_DIR: /Applications/Xcode_12.2.app
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
